### ISSUE TITLE
PLC proj file overwritten during tagging process

### ISSUE THREAD

**Issue by slacAWallace** [pcdshub/tc_release#4]
Entire PLC project file is being overwritten during tag. Should only be modifying a portion of the file.

**Comment by slacAWallace** [comment]
This is a problem with line-endings. 

Adding a .gitattribute file to your TC project will correct the issue. See:
[TwinCAT 3 Git Setup and Best Practices](https://confluence.slac.stanford.edu/display/PCDS/TwinCAT+3+Git+Setup+and+Best+Practices
)

**Comment by teddyrendahl** [comment]
Way to track it down!
